# Generated by Django 3.1.5 on 2021-01-14 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20210113_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default='Not assigned', on_delete=django.db.models.deletion.RESTRICT, related_name='assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
